// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlxmjzeczmabkjslbrzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseG1qemVjem1hYmtqc2xicnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTA5NzksImV4cCI6MjA3MjAyNjk3OX0.cIRUa7Tdw5-Ly2GfAG2s7BNLxmgKEmEem-_NWHJ6nhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});